### ISSUE TITLE
random seed causing jobs to fail?

### ISSUE THREAD

**Issue by Saannah** [goldman-gp-ebi/SWAMPy#6]
Hi! I am running SWAMPy on a set of distribution files and some of them fail with the following error:
`Traceback (most recent call last):
  File "/home/snaderi/SWAMPy/src/simulate_metagenome.py", line 397, in <module>
    amplicons,n_reads,vcf_errordf=add_PCR_errors(df_amplicons,genome_abundances,PRIMER_BED,WUHAN_REF,AMPLICONS_FOLDER,
  File "/home/snaderi/SWAMPy/src/PCR_error.py", line 221, in add_PCR_errors
    seq_pos_df=pd.DataFrame(dict(seq_pos=seq_pos,mut_indices=mut_indices))
  File "/home/snaderi/miniconda3/envs/SWAMPy/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/snaderi/miniconda3/envs/SWAMPy/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/home/snaderi/miniconda3/envs/SWAMPy/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/snaderi/miniconda3/envs/SWAMPy/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
`
I noticed, that by changing only the random seed number, the command finishes successfully.
This is the command I ran:

n_reads=5000000
python3 /home/snaderi/SWAMPy/src/simulate_metagenome.py  \
--genomes_file swampy_distributions/msa.fasta \
--genome_abundances swampy_distributions/abundance.txt \
--temp_folder tmp_folder/  \
--output_folder out_dir --autoremove \
--output_filename_prefix test_file \
--seed 45 \
--read_length 150 \
--primer_set a4 \
--seqSys HS25 --n_reads ${n_reads}

This command fails with the error above. If I change nothing but the seed and set it to 5455, it works fine.
I have attached the abundance file (it's a simple uniform abundance file where all genomes have the same abundance) and the genome file I used to run this command. (I had to ad a .txt extension to the fasta because GitHub won't allow me to upload a .fasta file)

I could go about finding a seed that works for my runs, but I would like to make sure there is no underlying issue!

Could you please help me with this issue?
Thanks :)

[abundance.txt](https://github.com/goldman-gp-ebi/SWAMPy/files/11183672/abundance.txt)
[msa.fasta.txt](https://github.com/goldman-gp-ebi/SWAMPy/files/11183673/msa.fasta.txt)

**Comment by rabiafidan** [comment]
Hi! 
Thanks for using SWAMPy and reporting the issue! We will look into this and reply soon.

Thank you for your patience!

**Comment by Saannah** [comment]
Hi!
Thank you so much!

**Comment by rabiafidan** [comment]
Hi Sana, 

The problem appears to be because of a single PCR error that falls onto an amplicon end that has deletion wrt Wuhan ref (credits to Will). If you have already run SWAMPy with seeds that work, it is fine to go ahead with the results. Otherwise, the latest commit should fix the problem (skips the said error and prints a warning).

Thank you again for reporting this, I am closing the issue assuming that it is fixed but feel free to reopen it otherwise.
